# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: Tombo\Ramos\App\Controller
#     type: attribute



ramos_controllers:
    resource: ../src/Ramos/App/Controller/
    type: annotation
